# Generated by Django 5.1.2 on 2024-12-03 08:04

import appWeb.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Especialidad')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'especialidad',
            },
        ),
        migrations.CreateModel(
            name='HoraDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(choices=[('odontologia', 'Odontología'), ('medicina_general', 'Medicina General'), ('retiro_insumos', 'Retiro de Insumos')], max_length=50)),
                ('hora', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HoraTomada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino'), ('o', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('enfermedad', models.CharField(max_length=200, verbose_name='Enfermedad')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('medico', models.CharField(max_length=100, verbose_name='Médico')),
                ('especialidad', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('lugar_de_atencion', models.CharField(max_length=100, verbose_name='Lugar de Atención')),
            ],
            options={
                'verbose_name': 'Hora Tomada',
                'verbose_name_plural': 'Horas Tomadas',
                'db_table': 'hora_tomada',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Tipo de Atencion')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tipo de Atencion',
                'verbose_name_plural': 'Tipos de Atenciones',
                'db_table': 'tipoatencion',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('doctor', 'Doctor'), ('patient', 'Paciente')], default='patient', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('rut', models.CharField(blank=True, max_length=12, null=True)),
                ('problema', models.TextField(blank=True, null=True)),
                ('especialidad', models.CharField(choices=[('odontologia', 'Odontología'), ('medicina_general', 'Medicina General'), ('retiro_insumos', 'Retiro de Insumos')], max_length=50)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.horadisponible')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=10, verbose_name='RUN')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('materno', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino'), ('o', 'Otro')], default='o', max_length=1)),
                ('enfermedad', models.CharField(max_length=200, verbose_name='Enfermedad')),
                ('fechaNac', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('foto', models.ImageField(blank=True, default='pacientes/paciente.png', null=True, upload_to=appWeb.models.Paciente.generar_nombre)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.especialidad')),
                ('tipoatencion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appWeb.tipo_atencion', verbose_name='Tipo de Atencion')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'paciente',
                'ordering': ['nombre', 'paterno', 'materno', 'tipoatencion', 'especialidad'],
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('nivel_riesgo', models.CharField(max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.paciente')),
            ],
        ),
    ]
