# Generated by Django 5.1.2 on 2024-12-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='diagnosticos',
            field=models.ManyToManyField(blank=True, related_name='pacientes', to='appWeb.diagnostico'),
        ),
    ]
