# Generated by Django 5.1.2 on 2024-12-03 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0002_paciente_diagnosticos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='diagnosticos',
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='nivel_riesgo',
            field=models.CharField(max_length=50, verbose_name='Nivel de riesgo'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='appWeb.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='tipo',
            field=models.CharField(max_length=100, verbose_name='Tipo de diagnóstico'),
        ),
    ]
