# Generated by Django 5.1.2 on 2024-12-03 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0003_remove_paciente_diagnosticos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='diagnosticos',
            field=models.ManyToManyField(blank=True, related_name='pacientes', to='appWeb.diagnostico'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='nivel_riesgo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.paciente'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
