# Generated by Django 5.1.2 on 2024-12-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0004_paciente_diagnosticos_alter_diagnostico_creado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoUrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=255, verbose_name='Nombre del Paciente')),
                ('enfermedad', models.CharField(max_length=255, verbose_name='Enfermedad')),
                ('nivel_riesgo', models.CharField(max_length=50, verbose_name='Nivel de Riesgo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Diagnóstico Urgente',
                'verbose_name_plural': 'Diagnósticos Urgentes',
                'db_table': 'diagnosticosurg',
            },
        ),
    ]
