# Generated by Django 5.1.2 on 2024-12-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0005_diagnosticourg'),
    ]

    operations = [
        migrations.AddField(
            model_name='horatomada',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
    ]
