# Generated by Django 5.1.2 on 2024-12-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0006_horatomada_correo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_atencion',
            options={'verbose_name': 'Tipo de Atención', 'verbose_name_plural': 'Tipos de Atenciones'},
        ),
        migrations.AddField(
            model_name='especialidad',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='tipo_atencion',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tipo_atencion',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del Tipo de Atención'),
        ),
    ]
