# Generated by Django 5.1.3 on 2024-12-10 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0008_horatomada_paciente_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horatomada',
            options={},
        ),
        migrations.RemoveField(
            model_name='horatomada',
            name='enfermedad',
        ),
        migrations.RemoveField(
            model_name='horatomada',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='horatomada',
            name='materno',
        ),
        migrations.RemoveField(
            model_name='horatomada',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='horatomada',
            name='paterno',
        ),
        migrations.RemoveField(
            model_name='horatomada',
            name='sexo',
        ),
        migrations.AlterModelTable(
            name='horatomada',
            table=None,
        ),
    ]
