# Generated by Django 5.1.3 on 2024-12-10 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0010_alter_horatomada_options_horatomada_enfermedad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horatomada',
            name='paciente',
        ),
    ]
