# Generated by Django 5.1.3 on 2024-12-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0011_remove_horatomada_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horatomada',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='horatomada',
            name='fecha_de_hora',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de hora'),
        ),
    ]
