# Generated by Django 5.1.3 on 2024-12-10 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0012_remove_horatomada_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horatomada',
            name='correo',
        ),
    ]
