# Generated by Django 5.1.3 on 2024-12-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0013_remove_horatomada_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horatomada',
            name='fecha_de_hora',
        ),
        migrations.AddField(
            model_name='horatomada',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='horatomada',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
