# Generated by Django 5.1.3 on 2024-12-11 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0014_remove_horatomada_fecha_de_hora_horatomada_correo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=12, verbose_name='RUN')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='medicos/', verbose_name='Fotografía')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.especialidad')),
                ('tipo_atencion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appWeb.tipo_atencion', verbose_name='Tipo de Atencion')),
            ],
        ),
    ]
