# Generated by Django 5.1.3 on 2024-12-11 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0015_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='tipo_atencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appWeb.tipo_atencion', verbose_name='Tipo de Atención'),
        ),
    ]
