# Generated by Django 5.1.3 on 2024-12-11 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0016_alter_medico_tipo_atencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horatomada',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appWeb.medico', verbose_name='Eliga Medico'),
        ),
        migrations.AlterField(
            model_name='horatomada',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.paciente'),
        ),
    ]
